# Generated by Django 2.2.2 on 2019-07-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=14)),
                ('Email', models.EmailField(max_length=40)),
                ('Phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=14)),
                ('Date', models.DateTimeField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='total_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=14)),
                ('Balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=14)),
                ('Date', models.DateTimeField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
